version: '3.8'
services:
  # Spring Boot アプリケーションのサービス
  app:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - ~/.gradle:/home/gradle/.gradle
    command: ./gradlew bootRun
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/quizdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password

  # PostgreSQL データベースのサービス
  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=quizdb
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: